version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - dbdevdata:/var/lib/data
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
volumes:
  dbdevdata:
